/* main.cpp ~ Main class for Knifesurge's Pokedex Application
 * Everything is run from this file (acts as a God file)
 */

#include <iostream>
#include <cstring>

using namespace std;

typedef struct
{
	char	name[15];
	char	type[10];
	int	poke_id;
}Poke;

void printPoke(Poke *poke);

int main()
{
	//Pokemon Declaration
	Poke bulbasaur;
	Poke ivysaur;
	Poke venusaur;
	Poke charmander;
	Poke charmeleon;
	Poke charizard;
	Poke squirtle;
	Poke wartortle;
	Poke blastoise;
	Poke caterpie;
	Poke metapod;
	Poke butterfree;
	Poke weedle;
	Poke kakuna;
	Poke beedrill;
	Poke pidgey;
	Poke pidgeotto;
	Poke pidgeot;
	Poke rattata;
	Poke raticate;
	Poke spearow;
	Poke fearow;
	Poke ekans;
	Poke arbok;
	Poke pikachu;
	Poke raichu;
	Poke sandshrew;
	Poke sandslash;
	Poke nidoranF;
	Poke nidorina;
	Poke nidoqueen;
	Poke nidoranM;
	Poke nidorino;
	Poke nidoking;
	Poke clefairy;
	Poke clefable;
	Poke vulpix;
	Poke ninetales;
	Poke jigglypuff;
	Poke wigglytuff;
	Poke zubat;
	Poke golbat;
	Poke oddish;
	Poke gloom;
	Poke vileplume;
	Poke paras;
	Poke parasect;
	Poke venonat;
	Poke venomoth;
	Poke diglett;
	Poke dugtrio;
	Poke meowth;
	Poke persian;
	Poke psyduck;
	Poke golduck;
	Poke mankey;
	Poke primeape;
	Poke growlithe;
	Poke arcanine;
	Poke poliwag;
	Poke poliwhirl;
	Poke poliwrath;
	Poke abra;
	Poke kadabra;
	Poke alakazam;
	Poke machop;
	Poke machoke;
	Poke machamp;
	Poke bellsprout;
	Poke weepinbell;
	Poke victreebel;
	Poke tentacool;
	Poke tentacruel;
	Poke geodude;
	Poke graveler;
	Poke golem;
	Poke ponyta;
	Poke rapidash;
	Poke slowpoke;
	Poke slowbro;
	Poke magnemite;
	Poke magneton;
	Poke farfetchd;
	Poke doduo;
	Poke dodrio;
	Poke seel;
	Poke dewgong;
	Poke grimer;
	Poke muk;
	Poke shellder;
	Poke cloyster;
	Poke gastly;
	Poke haunter;
	Poke gengar;
	Poke onix;
	Poke drowzee;
	Poke hypno;
	Poke krabby;
	Poke kingler;
	Poke voltorb;
	Poke electrode;
	Poke exeggcute;
	Poke exeggutor;
	Poke cubone;
	Poke marowak;
	Poke hitmonlee;
	Poke hitmonchan;
	Poke lickitung;
	Poke koffing;
	Poke weezing;
	Poke rhyhorn;
	Poke rhydon;
	Poke chansey;
	Poke tangela;
	Poke kangaskhan;
	Poke horsea;
	Poke seadra;
	Poke goldeen;
	Poke seaking;
	Poke staryu;
	Poke starmie;
	Poke mr_mime;
	Poke scyther;
	Poke jynx;
	Poke electabuzz;
	Poke magmar;
	Poke pinsir;
	Poke tauros;
	Poke magikarp;
	Poke gyarados;
	Poke lapras;
	Poke ditto;
	Poke eevee;
	Poke vaporean;
	Poke jolteon;
	Poke flareon;
	Poke porygon;
	Poke omanyte;
	Poke omastar;
	Poke kabuto;
	Poke kabutops;
	Poke aerodactyl;
	Poke snorlax;
	Poke articuno;
	Poke zapdos;
	Poke moltres;
	Poke dratini;
	Poke dragonair;
	Poke dragonite;
	Poke mewtwo;
	Poke mew; //#151

	//Fill Poke Struct
	strcpy(bulbasaur.name, "Bulbasaur");
	strcpy(bulbasaur.type, "Grass/Poison");
	bulbasaur.poke_id = 1;
	strcpy(ivysaur.name, "Ivysaur");
	strcpy(ivysaur.type, "Grass/Poison");
	ivysaur.poke_id = 2;
	strcpy(venusaur.name, "Venusaur");
	strcpy(venusaur.type, "Grass/Poison");
	venusaur.poke_id = 3;
	strcpy(charmander.name, "Charmander");
	strcpy(charmander.type, "Fire");
	charmander.poke_id = 4;
	strcpy(charmeleon.name, "Charmeleon");
	strcpy(charmeleon.type, "Fire");
	charmeleon.poke_id = 5;
	strcpy(charizard.name, "Charizard");
	strcpy(charizard.type, "Fire/Flying");
	charizard.poke_id = 6;
	strcpy(squirtle.name, "Squirtle");
	strcpy(squirtle.type, "Water");
	squirtle.poke_id = 7;
	strcpy(wartortle.name, "Wartortle");
	strcpy(wartortle.type, "Water");
	wartortle.poke_id = 8;
	strcpy(blastoise.name, "Blastoise");
	strcpy(blastoise.type, "Water");
	blastoise.poke_id = 9;
	strcpy(caterpie.name, "Caterpie");
	strcpy(caterpie.type, "Bug");
	caterpie.poke_id = 10;
	strcpy(metapod.name, "Metapod");
	strcpy(metapod.type, "Bug");
	metapod.poke_id = 11;
	strcpy(butterfree.name, "Butterfree");
	strcpy(butterfree.type, "Bug/Flying");
	butterfree.poke_id = 12;
	strcpy(weedle.name, "Weedle");
	strcpy(weedle.type, "Bug/Poison");
	weedle.poke_id = 13;
	strcpy(kakuna.name, "Kakuna");
	strcpy(kakuna.type, "Bug/Poison");
	kakuna.poke_id = 14;
	strcpy(beedrill.name, "Beedrill");
	strcpy(beedrill.type, "Bug/Poison");
	beedrill.poke_id = 15;
	strcpy(pidgey.name, "Pidgey");
	strcpy(pidgey.type, "Normal/Flying");
	pidgey.poke_id = 16;
	strcpy(pidgeotto.name, "Pidgeotto");
	strcpy(pidgeotto.type, "Normal/Flying");
	pidgeotto.poke_id = 17;
	strcpy(pidgeot.name, "Pidgeot");
	strcpy(pidgeot.type, "Normal/Flying");
	pidgeot.poke_id = 18;
	strcpy(rattata.name, "Rattata");
	strcpy(rattata.type, "Normal");
	rattata.poke_id = 19;
	strcpy(raticate.name, "Raticate");
	strcpy(raticate.type, "Normal");
	raticate.poke_id = 20;
	strcpy(spearow.name, "Spearow");
	strcpy(spearow.type, "Normal/Flying");
	spearow.poke_id = 21;
	strcpy(fearow.name, "Fearow");
	strcpy(fearow.type, "Normal/Flying");
	fearow.poke_id = 22;
	strcpy(ekans.name, "Ekans");
	strcpy(ekans.type, "Poison");
	ekans.poke_id = 23;
	strcpy(arbok.name, "Arbok");
	strcpy(arbok.type, "Poison");
	arbok.poke_id = 24;
	strcpy(pikachu.name, "Pikachu");
	strcpy(pikachu.type, "Electric");
	pikachu.poke_id = 25;
	strcpy(raichu.name, "Raichu");
	strcpy(raichu.type, "Electric");
	raichu.poke_id = 26;
	strcpy(sandshrew.name, "Sandshrew");
	strcpy(sandshrew.type, "Ground");
	sandshrew.poke_id = 27;
	strcpy(sandslash.name, "Sandslash");
	strcpy(sandslash.type, "Ground");
	sandslash.poke_id = 28;
	strcpy(nidoranF.name, "Nidoran F");
	strcpy(nidoranF.type, "Poison");
	nidoranF.poke_id = 29;
	strcpy(nidorina.name, "Nidorina");
	strcpy(nidorina.type, "Poison");
	nidorina.poke_id = 30;
	strcpy(nidoqueen.name, "Nidoqueen");
	strcpy(nidoqueen.type, "Poison/Ground");
	nidoqueen.poke_id = 31;
	strcpy(nidoranM.name, "Nidoran M");
	strcpy(nidoranM.type, "Poison");
	nidoranM.poke_id = 32;
	strcpy(nidorino.name, "Nidorino");
	strcpy(nidorino.type, "Poison");
	nidorino.poke_id = 33;
	strcpy(nidoking.name, "Nidoking");
	strcpy(nidoking.type, "Poison/Ground");
	nidoking.poke_id = 34;
	strcpy(clefairy.name, "Clefairy");
	strcpy(clefairy.type, "Normal");
	clefairy.poke_id = 35;
	strcpy(clefable.name, "Clefable");
	strcpy(clefable.type, "Normal");
	clefable.poke_id = 36;
	strcpy(vulpix.name, "Vulpix");
	strcpy(vulpix.type, "Fire");
	vulpix.poke_id = 37;
	strcpy(ninetales.name, "Ninetales");
	strcpy(ninetales.type, "Fire");
	ninetales.poke_id = 38;
	strcpy(jigglypuff.name, "Jigglypuff");
	strcpy(jigglypuff.type, "Normal");
	jigglypuff.poke_id = 39;
	strcpy(wigglytuff.name, "Wigglytuff");
	strcpy(wigglytuff.type, "Normal");
	wigglytuff.poke_id = 40;
	strcpy(zubat.name, "Zubat");
	strcpy(zubat.type, "Poison/Flying");
	zubat.poke_id = 41;
	strcpy(golbat.name, "Golbat");
	strcpy(golbat.type, "Poison/Flying");
	golbat.poke_id = 42;
	strcpy(oddish.name, "Oddish");
	strcpy(oddish.type, "Grass/Poison");
	oddish.poke_id = 43;
	strcpy(gloom.name, "Gloom");
	strcpy(gloom.type, "Grass/Poison");
	gloom.poke_id = 44;
	strcpy(vileplume.name, "Vileplume");
	strcpy(vileplume.type, "Grass/Poison");
	vileplume.poke_id = 45;
	strcpy(paras.name, "Paras");
	strcpy(paras.type, "Bug/Grass");
	paras.poke_id = 46;
	strcpy(parasect.name, "Parasect");
	strcpy(parasect.type, "Bug/Grass");
	parasect.poke_id = 47;
	strcpy(venonat.name, "Venonat");
	strcpy(venonat.type, "Bug/Poison");
	venonat.poke_id = 48;
	strcpy(venomoth.name, "Venomoth");
	strcpy(venomoth.type, "Bug/Poison");
	venomoth.poke_id = 49;
	strcpy(diglett.name, "Diglett");
	strcpy(diglett.type, "Ground");
	diglett.poke_id = 50;
	strcpy(dugtrio.name, "Dugtrio");
	strcpy(dugtrio.type, "Ground");
	dugtrio.poke_id = 51;
	strcpy(meowth.name, "Meowth");
	strcpy(meowth.type, "Normal");
	meowth.poke_id = 52;
	strcpy(persian.name, "Persian");
	strcpy(persian.type, "Normal");
	persian.poke_id = 53;
	strcpy(psyduck.name, "Psyduck");
	strcpy(psyduck.type, "Water");
	psyduck.poke_id = 54;
	strcpy(golduck.name, "Golduck");
	strcpy(golduck.type, "Water");
	golduck.poke_id = 55;
	strcpy(mankey.name, "Mankey");
	strcpy(mankey.type, "Fighting");
	mankey.poke_id = 56;
	strcpy(primeape.name, "Primeape");
	strcpy(primeape.type, "Fighting");
	primeape.poke_id = 57;
	strcpy(growlithe.name, "Growlithe");
	strcpy(growlithe.type, "Fire");
	growlithe.poke_id = 58;
	strcpy(arcanine.name, "Arcanine");
	strcpy(arcanine.type, "Fire");
	arcanine.poke_id = 59;
	strcpy(poliwag.name, "Poliwag");
	strcpy(poliwag.type, "Water");
	poliwag.poke_id = 60;
	strcpy(poliwhirl.name, "Poliwhirl");
	strcpy(poliwhirl.type, "Water");
	poliwhirl.poke_id = 61;
	strcpy(poliwrath.name, "Poliwrath");
	strcpy(poliwrath.type, "Water/Fighting");
	poliwrath.poke_id = 62;
	strcpy(abra.name, "Abra");
	strcpy(abra.type, "Psychic");
	abra.poke_id = 63;
	strcpy(kadabra.name, "Kadabra");
	strcpy(kadabra.type, "Psychic");
	kadabra.poke_id = 64;
	strcpy(alakazam.name, "Alakazam");
	strcpy(alakazam.type, "Psychic");
	alakazam.poke_id = 65;
	strcpy(machop.name, "Machop");
	strcpy(machop.type, "Fighting");
	machop.poke_id = 66;
	strcpy(machoke.name, "Machoke");
	strcpy(machoke.type, "Fighting");
	machoke.poke_id = 67;
	strcpy(machamp.name, "Machamp");
	strcpy(machamp.type, "Fighting");
	machamp.poke_id = 68;
	strcpy(bellsprout.name, "Bellsprout");
	strcpy(bellsprout.type, "Grass/Poison");
	bellsprout.poke_id = 69;
	strcpy(weepinbell.name, "Weepinbell");
	strcpy(weepinbell.type, "Grass/Poison");
	weepinbell.poke_id = 70;
	strcpy(victreebel.name, "Victreebel");
	strcpy(victreebel.type, "Grass/Poison");
	victreebel.poke_id = 71;
	strcpy(tentacool.name, "Tentacool");
	strcpy(tentacool.type, "Water/Poison");
	tentacool.poke_id = 72;
	strcpy(tentacruel.name, "Tentacruel");
	strcpy(tentacruel.type, "Water/Poison");
	tentacruel.poke_id = 73;
	strcpy(geodude.name, "Geodude");
	strcpy(geodude.type, "Rock/Ground");
	geodude.poke_id = 74;
	strcpy(graveler.name, "Graveler");
	strcpy(graveler.type, "Rock/Ground");
	graveler.poke_id = 75;
	strcpy(golem.name, "Golem");
	strcpy(golem.type, "Rock/Ground");
	golem.poke_id = 76;
	strcpy(ponyta.name, "Ponyta");
	strcpy(ponyta.type, "Fire");
	ponyta.poke_id = 77;
	strcpy(rapidash.name, "Rapidash");
	strcpy(rapidash.type, "Fire");
	rapidash.poke_id = 78;
	strcpy(slowpoke.name, "Slowpoke");
	strcpy(slowpoke.type, "Water/Psychic");
	slowpoke.poke_id = 79;
	strcpy(slowbro.name, "Slowbro");
	strcpy(slowbro.type, "Water/Psychic");
	slowbro.poke_id = 80;
	strcpy(magnemite.name, "Magnemite");
	strcpy(magnemite.type, "Electric/Steel");
	magnemite.poke_id = 81;
	strcpy(magneton.name, "Magneton");
	strcpy(magneton.type, "Electric/Steel");
	magneton.poke_id = 82;
	strcpy(farfetchd.name, "Farfetch'd");
	strcpy(farfetchd.type, "Normal/Flying");
	farfetchd.poke_id = 83;
	strcpy(doduo.name, "Doduo");
	strcpy(doduo.type, "Normal/Flying");
	doduo.poke_id = 84;
	strcpy(dodrio.name, "Dodrio");
	strcpy(dodrio.type, "Normal/Flying");
	dodrio.poke_id = 85;
	strcpy(seel.name, "Seel");
	strcpy(seel.type, "Water");
	seel.poke_id = 86;
	strcpy(dewgong.name, "Dewgong");
	strcpy(dewgong.type, "Water/Ice");
	dewgong.poke_id = 87;
	strcpy(grimer.name, "Grimer");
	strcpy(grimer.type, "Poison");
	grimer.poke_id = 88;
	strcpy(muk.name, "Muk");
	strcpy(muk.type, "Poison");
	muk.poke_id = 89;
	strcpy(shellder.name, "Shellder");
	strcpy(shellder.type, "Water");
	shellder.poke_id = 90;
	strcpy(cloyster.name, "Cloyster");
	strcpy(cloyster.type, "Water/Ice");
	cloyster.poke_id = 91;
	strcpy(gastly.name, "Gastly");
	strcpy(gastly.type, "Ghost/Poison");
	gastly.poke_id = 92;
	strcpy(haunter.name, "Haunter");
	strcpy(haunter.type, "Ghost/Poison");
	haunter.poke_id = 93;
	strcpy(gengar.name, "Gengar");
	strcpy(gengar.type, "Ghost/Poison");
	gengar.poke_id = 94;
	strcpy(onix.name, "Onix");
	strcpy(onix.type, "Rock/Ground");
	onix.poke_id = 95;
	strcpy(drowzee.name, "Drowzee");
	strcpy(drowzee.type, "Psychic");
	drowzee.poke_id = 96;
	strcpy(hypno.name, "Hypno");
	strcpy(hypno.type, "Psychic");
	hypno.poke_id = 97;
	strcpy(krabby.name, "Krabby");
	strcpy(krabby.type, "Water");
	krabby.poke_id = 98;
	strcpy(kingler.name, "Kingler");
	strcpy(kingler.type, "Water");
	kingler.poke_id = 99;
	strcpy(voltorb.name, "Voltorb");
	strcpy(voltorb.type, "Electric");
	voltorb.poke_id = 100;
	strcpy(electrode.name, "Electrode");
	strcpy(electrode.type, "Electric");
	electrode.poke_id = 101;
	strcpy(exeggcute.name, "Exeggcute");
	strcpy(exeggcute.type, "Grass/Psychic");
	exeggcute.poke_id = 102;
	strcpy(exeggutor.name, "Exeggutor");
	strcpy(exeggutor.type, "Grass/Psychic");
	exeggutor.poke_id = 103;
	strcpy(cubone.name, "Cubone");
	strcpy(cubone.type, "Ground");
	cubone.poke_id = 104;
	strcpy(marowak.name, "Marowak");
	strcpy(marowak.type, "Ground");
	marowak.poke_id = 105;
	strcpy(hitmonlee.name, "Hitmonlee");
	strcpy(hitmonlee.type, "Fighting");
	hitmonlee.poke_id = 106;
	strcpy(hitmonchan.name, "Hitmonchan");
	strcpy(hitmonchan.type, "Fighting");
	hitmonchan.poke_id = 107;
	strcpy(lickitung.name, "Lickitung");
	strcpy(lickitung.type, "Normal");
	lickitung.poke_id = 108;
	strcpy(koffing.name, "Koffing");
	strcpy(koffing.type, "Poison");
	koffing.poke_id = 109;
	strcpy(weezing.name, "Weezing");
	strcpy(weezing.type, "Poison");
	weezing.poke_id = 110;
	strcpy(rhyhorn.name, "Rhyhorn");
	strcpy(rhyhorn.type, "Ground/Rock");
	rhyhorn.poke_id = 111;
	strcpy(rhydon.name, "Rhydon");
	strcpy(rhydon.type, "Ground/Rock");
	rhydon.poke_id = 112;
	strcpy(chansey.name, "Chansey");
	strcpy(chansey.type, "Normal");
	chansey.poke_id = 113;
	strcpy(tangela.name, "Tangela");
	strcpy(tangela.type, "Grass");
	tangela.poke_id = 114;
	strcpy(kangaskhan.name, "Kangaskhan");
	strcpy(kangaskhan.type, "Normal");
	kangaskhan.poke_id = 115;
	strcpy(horsea.name, "Horsea");
	strcpy(horsea.type, "Water");
	horsea.poke_id = 116;
	strcpy(seadra.name, "Seadra");
	strcpy(seadra.type, "Water");
	seadra.poke_id = 117;
	strcpy(goldeen.name, "Goldeen");
	strcpy(goldeen.type, "Water");
	goldeen.poke_id = 118;
	strcpy(seaking.name, "Seaking");
	strcpy(seaking.type, "Water");
	seaking.poke_id = 119;
	strcpy(staryu.name, "Staryu");
	strcpy(staryu.type, "Water");
	staryu.poke_id = 120;
	strcpy(starmie.name, "Starmie");
	strcpy(starmie.type, "Water/Psychic");
	starmie.poke_id = 121;
	strcpy(mr_mime.name, "Mr. Mime");
	strcpy(mr_mime.type, "Psychic");
	mr_mime.poke_id = 122;
	strcpy(scyther.name, "Scyther");
	strcpy(scyther.type, "Bug/Flying");
	scyther.poke_id = 123;
	strcpy(jynx.name, "Jynx");
	strcpy(jynx.type, "Ice/Psychic");
	jynx.poke_id = 124;
	strcpy(electabuzz.name, "Electabuzz");
	strcpy(electabuzz.type, "Electric");
	electabuzz.poke_id = 125;
	strcpy(magmar.name, "Magmar");
	strcpy(magmar.type, "Fire");
	magmar.poke_id = 126;
	strcpy(pinsir.name, "Pinsir");
	strcpy(pinsir.type, "Bug");
	pinsir.poke_id = 127;
	strcpy(tauros.name, "Tauros");
	strcpy(tauros.type, "Normal");
	tauros.poke_id = 128;
	strcpy(magikarp.name, "Magikarp");
	strcpy(magikarp.type, "Water");
	magikarp.poke_id = 129;
	strcpy(gyarados.name, "Gyarados");
	strcpy(gyarados.type, "Water/Flying");
	gyarados.poke_id = 130;
	strcpy(lapras.name, "Lapras");
	strcpy(lapras.type, "Water/Ice");
	lapras.poke_id = 131;
	strcpy(ditto.name, "Ditto");
	strcpy(ditto.type, "Normal");
	ditto.poke_id = 132;
	strcpy(eevee.name, "Eevee");
	strcpy(eevee.type, "Normal");
	eevee.poke_id = 133;
	strcpy(vaporean.name, "Vaporeon");
	strcpy(vaporean.type, "Water");
	vaporean.poke_id = 134;
	strcpy(jolteon.name, "Jolteon");
	strcpy(jolteon.type, "Electric");
	jolteon.poke_id = 135;
	strcpy(flareon.name, "Flareon");
	strcpy(flareon.type, "Fire");
	flareon.poke_id = 136;
	strcpy(porygon.name, "Porygon");
	strcpy(porygon.type, "Normal");
	porygon.poke_id = 137;
	strcpy(omanyte.name, "Omanyte");
	strcpy(omanyte.type, "Rock/Water");
	omanyte.poke_id = 138;
	strcpy(omastar.name, "Omastar");
	strcpy(omastar.type, "Rock/Water");
	omastar.poke_id = 139;
	strcpy(kabuto.name, "Kabuto");
	strcpy(kabuto.type, "Rock/Water");
	kabuto.poke_id = 140;
	strcpy(kabutops.name, "Kabutops");
	strcpy(kabutops.type, "Rock/Water");
	kabutops.poke_id = 141;
	strcpy(aerodactyl.name, "Aerodactyl");
	strcpy(aerodactyl.type, "Rock/Flying");
	aerodactyl.poke_id = 142;
	strcpy(snorlax.name, "Snorlax");
	strcpy(snorlax.type, "Normal");
	snorlax.poke_id = 143;
	strcpy(articuno.name, "Articuno");
	strcpy(articuno.type, "Ice/Flying");
	articuno.poke_id = 144;
	strcpy(zapdos.name, "Zapdos");
	strcpy(zapdos.type, "Electric/Flying");
	zapdos.poke_id = 145;
	strcpy(moltres.name, "Moltres");
	strcpy(moltres.type, "Fire/Flying");
	moltres.poke_id = 146;
	strcpy(dratini.name, "Dratini");
	strcpy(dratini.type, "Dragon");
	dratini.poke_id = 147;
	strcpy(dragonair.name, "Dragonair");
	strcpy(dragonair.type, "Dragon");
	dragonair.poke_id = 148;
	strcpy(dragonite.name, "Dragonite");
	strcpy(dragonite.type, "Dragon/Flying");
	dragonite.poke_id = 149;
	strcpy(mewtwo.name, "Mewtwo");
	strcpy(mewtwo.type, "Psychic");
	mewtwo.poke_id = 150;
	strcpy(mew.name, "Mew");
	strcpy(mew.type, "Psychic");
	mew.poke_id = 151;

	//Declare variable to hold user input
	int id;

	//Array that holds every Poke, used to search for user input
	Poke pokemon[] = {bulbasaur,ivysaur,venusaur,charmander,charmeleon,charizard,squirtle,wartortle,blastoise,caterpie,metapod,butterfree,weedle,kakuna,beedrill,pidgey,pidgeotto,pidgeot,rattata,raticate,spearow,fearow,ekans,arbok,pikachu,raichu,sandshrew,sandslash,nidoranF,nidorina,nidoqueen,nidoranM,nidorino,nidoking,clefairy,clefable,vulpix,ninetales,jigglypuff,wigglytuff,zubat,golbat,oddish,gloom,vileplume,paras,parasect,venonat,venomoth,diglett,dugtrio,meowth,persian,psyduck,golduck,mankey,primeape,growlithe,arcanine,poliwag,poliwhirl,poliwrath,abra,kadabra,alakazam,machop,machoke,machamp,bellsprout,weepinbell,victreebel,tentacool,tentacruel,geodude,graveler,golem,ponyta,rapidash,slowpoke,slowbro,magnemite,magneton,farfetchd,doduo,dodrio,seel,dewgong,grimer,muk,shellder,cloyster,gastly,haunter,gengar,onix,drowzee,hypno,krabby,kingler,voltorb,electrode,exeggcute,exeggutor,cubone,marowak,hitmonlee,hitmonchan,lickitung,koffing,weezing,rhyhorn,rhydon,chansey,tangela,kangaskhan,horsea,seadra,goldeen,seaking,staryu,starmie,mr_mime,scyther,jynx,electabuzz,magmar,pinsir,tauros,magikarp,gyarados,lapras,ditto,eevee,vaporean,jolteon,flareon,porygon,omanyte,omastar,kabuto,kabutops,aerodactyl,snorlax,articuno,zapdos,moltres,dratini,dragonair,dragonite,mewtwo,mew};

	//Whether or not to continue looping
	int run = 1;
	while(run == 1)
	{
		cout << "Enter the ID for the Pokemon(-1 to Exit): ";
		if(cin >> id)
		{
			//valid input
			//Loop over input to determine what Pokemon to print based on what number the user entered
			for(int i=0;i<152;i++)
			{
				Poke poke = pokemon[i];
				if(id == -1)
				{
					run = 0;
					break;
				}
				if(id == poke.poke_id)
				{
					printPoke(&poke);
					break;
				}
			}
		} else {
			//not a valid input
			cerr << "Poke not found, please try a different name" << endl;
			cin.clear();
			cin.ignore(1000, '\n');	//Discard the next 1000 characters or a new line, which ever comes first . Empties input buffer
		}
	}

	return 0;
}

void printPoke(Poke *poke)
{
	cout << "Name: " << poke->name << endl;
	cout << "Type: " << poke->type << endl;
	cout << "ID: " << poke->poke_id << endl;
